{
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (builtins) lessThan sort;
  inherit (lib) mkEnableOption mkIf mkOption;
  inherit (lib.strings) join;
  inherit (lib.types) listOf;
  inherit (templateLib.formatters) autoGeneratedComment;
  inherit (templateLib.types) gitignorePattern;

  cfg = config.template.gitignore;
in
{
  options.template.gitignore = {
    enable = mkEnableOption "enable";

    ignore = mkOption {
      type = listOf gitignorePattern;
      default = [ ];
    };
  };

  config = mkIf cfg.enable {
    files.".gitignore" = {
      copyMode = "copy";
      text = ''
        # ${autoGeneratedComment}

        ${join "\n" (sort lessThan config.template.gitignore.ignore)}
      '';
    };

    template.gitignore.ignore = [
      "*~"
      ".devenv*"
      "devenv.local.nix"
      "devenv.local.yaml"
      ".direnv"
    ];
  };
}
