{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf mkOption;
  inherit (lib.types) package;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment formatYAML;
  inherit (templateLib.types) yaml;

  cfg = config.template.tools.actionlint;

  configFile = ".github/actionlint.yaml";
in
{
  options.template.tools.actionlint = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.actionlint;
    };

    config = mkOption {
      type = yaml;
      default = { };
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    git-hooks.hooks.actionlint = {
      enable = true;
      name = "github actions: lint";
      package = cfg.package;
    };

    files."${configFile}".source = formatYAML {
      inherit config;
      filename = configFile;
      data = prune cfg.config;
      comment = autoGeneratedComment;
    };
  };
}
