{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib)
    mkEnableOption
    mkIf
    mkOption
    mkOrder
    ;
  inherit (lib.types) lines package;
  inherit (templateLib.formatters) autoGeneratedComment;

  cfg = config.template.tools.gitlint;
  configFile = ".gitlint";
in
{
  options.template.tools.gitlint = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.gitlint;
    };

    config = mkOption {
      type = lines;
      default = "";
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    files."${configFile}".text = cfg.config;

    git-hooks.hooks.gitlint = {
      enable = true;
      name = "general: check commit message";
      package = cfg.package;
    };

    template = {
      gitignore.ignore = [ configFile ];

      tools.gitlint.config = mkOrder 0 ''
        # ${autoGeneratedComment}

        [general]
        ignore=body-is-missing
      '';
    };
  };
}
