{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf mkOption;
  inherit (lib.types) package;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment formatYAML;
  inherit (templateLib.types) yaml;

  cfg = config.template.tools.zizmor;

  configFile = ".github/zizmor.yaml";
in
{
  options.template.tools.zizmor = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.zizmor;
    };

    config = mkOption {
      type = yaml;
      default = { };
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    git-hooks.hooks.zizmor = {
      enable = true;
      name = "github actions: security";
      package = cfg.package;
      args = [
        "--pedantic"
        "--no-progress"
      ];
      require_serial = true;
    };

    files."${configFile}".source = formatYAML {
      inherit config;
      filename = configFile;
      data = prune cfg.config;
      comment = autoGeneratedComment;
    };
  };
}
