{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (builtins) lessThan sort;
  inherit (lib)
    getExe
    mkDefault
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    ;
  inherit (lib.strings) join;
  inherit (lib.types) listOf nonEmptyStr package;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment;
  inherit (templateLib.types) gitignorePattern yaml;

  cfg = config.template.tools.prettier;
  hooks = config.git-hooks.hooks;
  ignoreFile = ".prettierignore";
  configFile = ".prettierrc";
in
{
  options.template.tools.prettier = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.prettier;
    };

    ignore = mkOption {
      type = listOf gitignorePattern;
      default = [ ];
    };

    config = mkOption {
      type = yaml;
      default = { };
    };

    formatCommand = mkOption {
      type = nonEmptyStr;
      internal = true;
      readOnly = true;
    };
  };

  config = mkMerge [
    (mkIf cfg.enable {
      packages = [ cfg.package ];

      files = {
        "${ignoreFile}".text = ''
          # ${autoGeneratedComment}

        ''
        + (join "\n" (sort lessThan cfg.ignore));
        # We can't use formatYAML here, because it relies on this config and
        # causes infinite recursion
        "${configFile}".yaml = prune cfg.config;
      };

      git-hooks.hooks.prettier.enable = true;

      template = {
        gitignore.ignore = [
          ignoreFile
          configFile
        ];

        # Prettier uses .editorconfig if it exists
        tools.editorconfig.enable = mkDefault true;
      };
    })
    {
      git-hooks.hooks.prettier = {
        name = "general: prettier";
        package = cfg.package;
        entry = cfg.formatCommand;
      };

      template.tools.prettier.formatCommand = "${getExe hooks.prettier.package} --write --ignore-unknown";
    }
  ];
}
