{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib)
    getExe
    mkEnableOption
    mkIf
    mkOption
    ;
  inherit (lib.types) package toml;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment formatTOML;

  cfg = config.template.tools.gitleaks;
  hooks = config.git-hooks.hooks;
  configFile = ".gitleaks.toml";
in
{
  options.template.tools.gitleaks = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.gitleaks;
    };

    config = mkOption {
      type = toml;
      default = { };
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    files."${configFile}".source = formatTOML {
      inherit config;
      filename = configFile;
      data = prune cfg.config;
      comment = autoGeneratedComment;
    };

    git-hooks.hooks.gitleaks = {
      enable = true;
      name = "general: check for committed secrets";
      package = cfg.package;
      entry = "${getExe hooks.gitleaks.package} git --pre-commit --redact --staged --verbose";
      pass_filenames = false;
    };

    template = {
      gitignore.ignore = [ configFile ];

      tools.gitleaks.config = {
        extend.useDefault = true;
      };
    };
  };
}
