{ pkgs, lib }:
let
  inherit (pkgs) runCommandLocal writeText;
  inherit (pkgs.writers) writeJSON writeTOML writeYAML;
  inherit (lib.attrsets) optionalAttrs recursiveUpdate;
  inherit (lib.lists) optional;
  inherit (lib.strings) escapeShellArg join;

  maybeComment = prefix: comment: if comment != null then "${prefix} ${comment}" else null;

  formatData =
    {
      filename,
      data,
      writer,
      formatCommand,
      comment ? null,
      preCommands ? [ ],
    }:
    let
      raw = writer filename data;
    in
    runCommandLocal filename { } (
      join "\n" (
        (optional (preCommands != [ ]) (join "\n" preCommands))
        ++ (optional (comment != null) ''
          printf '%s\n\n' ${escapeShellArg comment} >$out
        '')
        ++ [
          ''
            cat ${escapeShellArg raw} >>$out

            ${formatCommand} $out
          ''
        ]
      )
    );

  formatWithPrettier =
    {
      config,
      filename,
      data,
      writer,
      comment ? null,
    }:
    let
      prettierConfigFile = writeYAML ".prettierrc" config.template.tools.prettier.config;
    in
    formatData {
      inherit
        filename
        data
        writer
        comment
        ;
      formatCommand = config.template.tools.prettier.formatCommand;
      preCommands = [
        "printf '%s\n' ${escapeShellArg config.template.tools.editorconfig.config} >.editorconfig"
        "cp ${prettierConfigFile} .prettierrc"
      ];
    };

  formatJSON =
    {
      config,
      filename,
      data,
    }:
    formatWithPrettier {
      inherit config filename data;
      writer = writeJSON;
    };

  formatMarkdown =
    {
      config,
      filename,
      text,
    }:
    formatWithPrettier {
      inherit config filename;
      data = text;
      writer = writeText;
    };

  formatTOML =
    {
      config,
      filename,
      data,
      comment ? null,
      tombiConfig ? null,
    }:
    let
      resolvedTombiConfig = recursiveUpdate config.template.tools.tombi.config (
        optionalAttrs (tombiConfig != null) tombiConfig
      );
      tombiConfigFile = writeTOML "tombi.toml" resolvedTombiConfig;
    in
    formatData {
      inherit filename data;
      writer = writeTOML;
      formatCommand = "${config.template.tools.tombi.formatCommand} --offline";
      preCommands = [ "cp ${tombiConfigFile} tombi.toml" ];
      comment = maybeComment "#" comment;
    };

  formatYAML =
    {
      config,
      filename,
      data,
      comment ? null,
    }:
    formatWithPrettier {
      inherit config filename data;
      writer = writeYAML;
      comment = maybeComment "#" comment;
    };

  autoGeneratedComment = "Auto-generated; edit devenv.nix instead";
in
{
  inherit
    autoGeneratedComment
    formatJSON
    formatMarkdown
    formatTOML
    formatYAML
    ;
}
