{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf mkOption;
  inherit (lib.types) listOf package;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment formatYAML;
  inherit (templateLib.types) gitignorePattern yaml;

  cfg = config.template.tools.yamllint;
  configFile = ".yamllint.yaml";
in
{
  options.template.tools.yamllint = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.yamllint;
    };

    config = mkOption {
      type = yaml;
      default = { };
    };

    ignore = mkOption {
      type = listOf gitignorePattern;
      default = [ ];
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    files."${configFile}".source = formatYAML {
      inherit config;
      filename = configFile;
      data = prune cfg.config;
      comment = autoGeneratedComment;
    };

    git-hooks.hooks.yamllint = {
      enable = true;
      name = "yaml: lint";
      package = cfg.package;
    };

    template = {
      gitignore.ignore = [ configFile ];

      tools.yamllint = {
        config = {
          extends = "default";
          rules = {
            braces = {
              forbid = false;
              min-spaces-inside = 0;
              max-spaces-inside = 0;
              min-spaces-inside-empty = 0;
              max-spaces-inside-empty = 0;
            };
            brackets = {
              forbid = false;
              min-spaces-inside = 0;
              max-spaces-inside = 0;
              min-spaces-inside-empty = 0;
              max-spaces-inside-empty = 0;
            };
            comments = {
              require-starting-space = true;
              ignore-shebangs = true;
              min-spaces-from-content = 1; # for compatibility with prettier
            };
            document-start = "disable";
            line-length = "disable";
          };
          ignore = cfg.ignore;
        };
      };
    };
  };
}
