{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib)
    getExe
    mkEnableOption
    mkIf
    mkOption
    ;
  inherit (lib.strings) optionalString;
  inherit (lib.types)
    listOf
    nonEmptyStr
    nullOr
    package
    ;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment formatYAML;
  inherit (templateLib.types) relativePath yaml;

  cfg = config.template.tools.buf;
  hooks = config.git-hooks.hooks;
  configFile = "${optionalString (cfg.root != null) "${cfg.root}/"}buf.yaml";
in
{
  options.template.tools.buf = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.buf;
    };

    root = mkOption {
      type = nullOr relativePath;
      default = null;
    };

    disableRules = mkOption {
      type = listOf nonEmptyStr;
      default = [ ];
    };

    config = mkOption {
      type = yaml;
      default = { };
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    files."${configFile}".source = formatYAML {
      inherit config;
      filename = configFile;
      data = prune cfg.config;
      comment = autoGeneratedComment;
    };

    git-hooks.hooks = {
      buf-lint = {
        enable = true;
        name = "protobuf: lint";
        package = cfg.package;
        entry = "${getExe hooks.buf-format.package} lint";
        types = [ "proto" ];
      };
      buf-format = {
        enable = true;
        name = "protobuf: format";
        package = cfg.package;
        entry = "${getExe hooks.buf-format.package} format --write";
        types = [ "proto" ];
      };
    };

    template = {
      tools.buf.config = {
        version = "v2";
        lint = {
          use = [ "BASIC" ];
          except = cfg.disableRules;
        };
      };

      gitignore.ignore = [ configFile ];
    };
  };
}
