{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (lib)
    getExe
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    ;
  inherit (lib.types) nonEmptyStr package toml;
  inherit (templateLib) prune;
  inherit (templateLib.formatters) autoGeneratedComment formatTOML;

  cfg = config.template.tools.tombi;
  hooks = config.git-hooks.hooks;

  configFile = ".tombi.toml";
in
{
  options.template.tools.tombi = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.tombi;
    };

    config = mkOption {
      type = toml;
      default = { };
    };

    formatCommand = mkOption {
      type = nonEmptyStr;
      internal = true;
      readOnly = true;
    };
  };

  config = mkMerge [
    (mkIf cfg.enable {
      packages = [ cfg.package ];

      files."${configFile}".source = formatTOML {
        inherit config;
        filename = configFile;
        data = prune cfg.config;
        comment = autoGeneratedComment;
      };

      git-hooks.hooks = {
        tombi-lint = {
          enable = true;
          name = "toml: lint";
          package = cfg.package;
          entry = "${getExe hooks.tombi-lint.package} lint";
          types_or = [ "toml" ];
        };
        tombi-format.enable = true;
      };

      template.gitignore.ignore = [ configFile ];
    })
    {
      git-hooks.hooks.tombi-format = {
        name = "toml: format";
        package = cfg.package;
        entry = cfg.formatCommand;
        types_or = [ "toml" ];
      };

      template.tools.tombi.formatCommand = "${getExe hooks.tombi-format.package} format";
    }
  ];
}
