{
  pkgs,
  lib,
  templateLib,
  config,
  ...
}:
let
  inherit (builtins) lessThan sort;
  inherit (lib) mkEnableOption mkIf mkOption;
  inherit (lib.strings) join;
  inherit (lib.types) listOf nonEmptyStr package;
  inherit (templateLib.formatters) autoGeneratedComment;

  cfg = config.template.tools.shellcheck;
  configFile = ".shellcheckrc";
in
{
  options.template.tools.shellcheck = {
    enable = mkEnableOption "enable";

    package = mkOption {
      type = package;
      default = pkgs.shellcheck;
    };

    config = mkOption {
      type = listOf nonEmptyStr;
      default = [ ];
    };

    disableRules = mkOption {
      type = listOf nonEmptyStr;
      default = [ ];
    };
  };

  config = mkIf cfg.enable {
    packages = [ cfg.package ];

    files."${configFile}".text = ''
      # ${autoGeneratedComment}

    ''
    + (join "\n" cfg.config);

    git-hooks.hooks.shellcheck = {
      enable = true;
      name = "shell: lint";
      package = cfg.package;
      exclude_types = [ "zsh" ];
      require_serial = true;
    };

    template = {
      gitignore.ignore = [ configFile ];

      tools.shellcheck = {
        config = [ "disable=${join "," (sort lessThan cfg.disableRules)}" ];

        disableRules = [
          "SC1090"
          "SC1091"
        ];
      };
    };
  };
}
